language: c++

services:
  - docker

before_install:
  - docker build -t icluesu2020/nlnum:latest .
  - docker run --name nlnum_bash --rm -it -d icluesu2020/nlnum:latest bash
  - docker ps

script:
  - ls
  - pwd
  - docker exec -d nlnum_bash 'cmake -Wno-dev -DCMAKE_BUILD_TYPE=Release --build cmake-build-release --target test-nlnum -- -j 2 .'
  - docker exec -d nlnum_bash 'time ./cmake-build-release/tests/cmake-build-debug/test-nlnum'
